import assert from 'node:assert/strict'
import { tableGraph, visibleTableIds, tableId, matchesTable } from '../../utils/tableGraph.ts'
const table = (id, name, connection_id = 'a', schema = 'public', fks = []) => ({ id, name, connection_id, metadata_json: { schema }, fks, is_active: false })
const fk = (target, col = 'foreign_id') => ({ references_name: target, column: { name: col }, references_column: { name: 'id' } })
const rows = [table('o', 'orders', 'a', 'public', [fk('customers'), fk('customers', 'billing_id'), fk('missing')]), table('c', 'customers'), table('other', 'customers', 'b'), table('i', 'items', 'a', 'public', [fk('orders'), fk('products')]), table('p', 'products'), table('s', 'staff', 'a', 'public', [fk('staff')])]
const graph = tableGraph(rows)
assert.deepEqual([...graph.neighbors.get('o')].sort(), ['c', 'i'])
assert.equal(graph.links.find(l => l.source === 'o').columns.length, 2)
assert.equal(graph.unresolved.get('o'), 1)
assert.deepEqual([...visibleTableIds(new Set(['o']), graph.neighbors, new Set())].sort(), ['c', 'i', 'o'])
assert.deepEqual([...visibleTableIds(new Set(['o', 'i']), graph.neighbors, new Set())].sort(), ['c', 'i', 'o', 'p'])
assert.deepEqual([...visibleTableIds(new Set(['o']), graph.neighbors, new Set(['p']))].sort(), ['c', 'i', 'o', 'p'])
assert.equal(graph.links.filter(l => l.source === 's' && l.target === 's').length, 1)
const collision = tableGraph([table('x', 'logs', 'a', 'public', [fk('customers')]), table('c1', 'customers'), table('c2', 'customers', 'a', 'billing')])
assert.equal(collision.links[0].target, 'c1')
assert.notEqual(tableId({...rows[0],id:undefined}), tableId({...rows[0],id:undefined,connection_id:'b'}))
assert.equal(matchesTable(rows[0], {search:'ord_rs', selected_state:'selected'}, true), true)
assert.equal(matchesTable(rows[0], {connection:['b']}), false)
const keyed = (id, name, connection, columns) => ({...table(id, name, connection), columns:columns.map(name=>({name,dtype:'INTEGER'}))})
const source = keyed('order','orders','a',['id','customer_id'])
const target = keyed('customer','customers','b',['id'])
const suggested = tableGraph([source,target])
assert.equal(suggested.links.length,1)
assert.equal(suggested.links[0].suggested,true)
assert.deepEqual([...visibleTableIds(new Set(['order']),suggested.neighbors,new Set())],['order','customer'])
assert.equal(tableGraph([source,target,{...target,id:'ambiguous',connection_id:'c'}]).links.length,0)
assert.equal(tableGraph([source,{...target,columns:[{name:'id',dtype:'TEXT'}]}]).links.length,0)
assert.equal(tableGraph([keyed('unrelated','logs','a',['id']),target]).links.length,0)
assert.equal(tableGraph([source,target,{...target,id:'local',connection_id:'a'}]).links[0].target,'local')
assert.equal(tableGraph([{...source,fks:[fk('missing','customer_id')]},target]).links.length,0)
const many = Array.from({length:1000},(_,i)=>keyed(`archive-${i}`,`archive_${i}`,'a',['id']))
const started = performance.now()
assert.equal(tableGraph([...many,source,target]).links.length,1)
assert.ok(performance.now()-started < 1000,'1000-table graph should remain interactive')
console.log('PASS: graph identity, declared/suggested relationships, ambiguity, three states, filters, and 1000-table catalog')
