import { chromium } from '@playwright/test';
const origin='http://localhost:3000';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const ctx=await b.newContext({viewport:{width:1500,height:950}}); const page=await ctx.newPage();
const errs=[]; page.on('pageerror',e=>errs.push('PAGEERR: '+e.message));
await page.goto(`${origin}/users/sign-in`,{waitUntil:'networkidle'}).catch(()=>{});
await page.fill('#email','admin@example.com'); await page.fill('#password','Password123!');
await Promise.all([page.waitForNavigation({waitUntil:'networkidle'}).catch(()=>{}),page.click('button[type=submit]')]);
await page.waitForTimeout(1500);
await page.goto(`${origin}/settings/models`,{waitUntil:'networkidle'}).catch(()=>{});
await page.waitForTimeout(2500);
const rows=page.locator('table tbody tr'); console.log('rows:',await rows.count());
const lastCellBtn=rows.first().locator('td').last().locator('button');
console.log('actions btn count:',await lastCellBtn.count());
const t0=Date.now();
await lastCellBtn.first().click({timeout:5000}).catch(e=>console.log('click err',e.message));
await page.waitForTimeout(1000);
// menu items visible?
const menuItems=await page.getByText('Set as default', {exact:false}).count().catch(()=>0);
console.log('dropdown opened in', Date.now()-t0,'ms; menu-ish items:', menuItems);
await page.screenshot({path:'../media/pr/auto-model-routing/05-actions-open.png'});
console.log('errors:',JSON.stringify(errs));
await ctx.close(); await b.close();
