apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels: {team: payments, env: staging}
---
apiVersion: v1
kind: Namespace
metadata:
  name: inventory
  labels: {team: supply-chain, env: staging}
