// Real browser workflows against seeded reports, never a fake query transport.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..');const {chromium}=require(path.join(root,'frontend/node_modules/playwright'));
const run=process.env.BOW_DATA_APP_RUN||'/tmp/bow-data-app-run';const apps=JSON.parse(fs.readFileSync(path.join(run,'apps/manifest.json')));
const evidence=path.join(root,'media/pr/data-app-generation');fs.mkdirSync(evidence,{recursive:true});
(async()=>{const b=await chromium.launch();const ctx=await b.newContext({storageState:path.join(run,'storage.json'),viewport:{width:1440,height:1100},recordVideo:{dir:path.join(run,'videos'),size:{width:1440,height:1100}}});const p=await ctx.newPage();const errors=[];const requests=[];const results=[];
p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/\/queries\/[^/]+\/run/.test(r.url())&&r.method()==='POST')requests.push({url:r.url(),body:r.postDataJSON()})});
async function open(slug){await p.goto('http://localhost:3000/r/'+apps[slug].report_id);await p.locator('iframe').first().waitFor();const el=await p.locator('iframe').first().elementHandle();const f=await el.contentFrame();await f.locator('#root h1').waitFor({timeout:60000});await f.waitForFunction(()=>window.__paramStore&&!window.__paramStore.isLoading(),{timeout:60000});await f.evaluate(()=>{window.__testMount='preserved'});return f}
async function settled(f,values){await f.waitForFunction(expected=>{const d=window.ARTIFACT_DATA;const store=window.__paramStore;return d&&store&&!store.isLoading()&&Object.keys(expected).every(k=>JSON.stringify(d.params?.values?.[k])===JSON.stringify(expected[k]))},values,{timeout:60000});assert.equal(await f.evaluate(()=>window.__testMount),'preserved')}
async function shot(slug,suffix='desktop'){await p.screenshot({path:path.join(evidence,slug+'-'+suffix+'.png'),fullPage:true})}
try{
 let f=await open('commerce');await shot('commerce','initial-state');
 const n=requests.length;
 await f.locator('select').selectOption('Europe');await f.locator('input[type=number]').fill('800');await f.locator('input[type=date]').nth(0).fill('2026-03-01');await f.locator('input[type=date]').nth(1).fill('2026-04-30');await f.getByRole('button',{name:'Marketplace',exact:true}).click();await f.getByRole('button',{name:'Apply filters',exact:true}).click();
 await settled(f,{region:'Europe',min_order:800,period:{from:'2026-03-01',to:'2026-04-30'},channels:['Direct','Partner']});
 let data=await f.evaluate(()=>window.ARTIFACT_DATA);const customers=data.visualizations.find(v=>v.title==='Customer portfolio').rows;assert.ok(customers.length);assert.ok(customers.every(r=>r.region==='Europe'));let sums=data.visualizations.map(v=>v.rows.reduce((s,r)=>s+Number(r.revenue||0),0));assert.ok(sums.every(s=>Math.abs(s-sums[0])<.1));assert.equal(new Set(requests.slice(n).map(r=>r.url)).size,3);results.push('Commerce: four combined typed parameters rerun all three real queries with consistent totals; iframe state preserved');
 await f.getByRole('button',{name:'Portfolio table',exact:true}).click();await f.locator('tbody tr').first().waitFor();await shot('commerce','filtered-table');
 await f.getByRole('button',{name:'Customer detail',exact:true}).click();await f.locator('input[type=number]').fill('10000000');await f.getByRole('button',{name:'Apply filters',exact:true}).click();await settled(f,{min_order:10000000});data=await f.evaluate(()=>window.ARTIFACT_DATA);assert.ok(data.visualizations.every(v=>v.rows.length===0));await shot('commerce','empty');results.push('Commerce: empty backend results render safely');
 // Recovery through the same visible controls.
 await f.locator('input[type=number]').fill('0');await f.locator('select').selectOption('');await f.locator('input[type=date]').nth(0).fill('2026-01-01');await f.locator('input[type=date]').nth(1).fill('2026-06-30');await f.getByRole('button',{name:'Marketplace',exact:true}).click();await f.getByRole('button',{name:'Apply filters',exact:true}).click();await settled(f,{region:null,min_order:0});await shot('commerce');
 f=await open('catalog');await shot('catalog','initial-state');
 await f.locator('.album-row').nth(2).click();const selected=await f.locator('.detail-title').innerText();await f.locator('select').selectOption('Jazz');await settled(f,{genre:'Jazz'});assert.equal(await f.locator('.detail-title').innerText(),selected);assert.ok((await f.evaluate(()=>window.ARTIFACT_DATA.visualizations[0].rows)).every(r=>r.genre==='Jazz'));results.push('Catalog: selection survives a supported backend filter');
 await f.getByPlaceholder('Album, artist, or track').fill('Ada');await settled(f,{search:'Ada'});assert.ok(await f.locator('.album-row').count());await f.locator('input[type=number]').nth(0).fill('1.3');await f.locator('input[type=number]').nth(1).fill('3');await settled(f,{max_price:1.3,min_minutes:3});await shot('catalog','filtered');
 await f.getByPlaceholder('Album, artist, or track').fill('no-such-record');await settled(f,{search:'no-such-record'});assert.equal(await f.locator('.album-row').count(),0);await shot('catalog','empty');await f.getByRole('button',{name:'Clear / reset',exact:true}).click();await settled(f,{search:'',genre:null,max_price:2,min_minutes:0});assert.equal(await f.locator('.album-row').count(),24);results.push('Catalog: search, numeric filters, empty state and reset execute against the full backend');
 // Exercise backend validation through the same bridge; test-only injection cannot bypass it.
 await f.evaluate(()=>window.__paramStore.setParam('max_price','invalid-number'));await f.waitForFunction(()=>!!window.__paramStore.getError(),{timeout:60000});await f.locator('.lr-error').waitFor();await shot('catalog','error');assert.match(await f.locator('.lr-error').innerText(),/number|numeric|price/i);await f.getByRole('button',{name:'Clear / reset',exact:true}).click();await settled(f,{max_price:2});assert.equal(await f.evaluate(()=>window.__paramStore.getError()),null);results.push('Catalog: backend type errors remain visible through data delivery and recover on valid input');await shot('catalog');
 f=await open('reps');await shot('reps','initial-state');await f.locator('.ro-rep-row').nth(1).click();
 await f.getByRole('button',{name:'Weekly view',exact:true}).click();await f.locator('[_echarts_instance_]').waitFor();await f.locator('select').selectOption('Europe');await settled(f,{region:'Europe'});assert.ok(await f.locator('[_echarts_instance_]').count());await shot('reps','weekly-filtered');await f.getByRole('button',{name:'Representatives',exact:true}).click();results.push('Representative app: selection, weekly tab and backend filters work without remounting');
 // Two dispatched changes: wait for the first request to start, then change again.
 const started=p.waitForRequest(r=>/\/queries\/[^/]+\/run/.test(r.url())&&r.method()==='POST');await f.locator('select').selectOption('North America');await started;await f.locator('select').selectOption('Asia Pacific');await settled(f,{region:'Asia Pacific'});await f.waitForFunction(()=>window.ARTIFACT_DATA.visualizations.filter(v=>v.title!=='Weekly performance').every(v=>v.rows.every(r=>r.region==='Asia Pacific')));results.push('Rapid dispatched parameter changes settle on the newest region');await f.locator('select').selectOption('');await settled(f,{region:null});await shot('reps');
 for(const slug of ['commerce','catalog','reps'])for(const width of [960,400]){
  await p.setViewportSize({width,height:1100});f=await open(slug);await f.waitForFunction(()=>document.fonts.status==='loaded');
  const overflow=await f.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:document.documentElement.clientWidth}));assert.ok(overflow.scroll<=overflow.width+2,JSON.stringify({slug,width,overflow}));await shot(slug,String(width));results.push(slug+': no horizontal page overflow at '+width+'px');
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(run,'ui-results.json'),JSON.stringify({results,requestCount:requests.length,errors},null,2));console.log(JSON.stringify({results,requestCount:requests.length,errors},null,2));
}catch(e){await p.screenshot({path:path.join(run,'ui-failure.png')});fs.writeFileSync(path.join(run,'ui-failure.json'),JSON.stringify({message:e.message,results,errors,requests},null,2));throw e}finally{await ctx.close();await b.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
