import { createRequire } from 'node:module';
const { chromium } = createRequire(new URL('../../../frontend/package.json', import.meta.url))('playwright');
import fs from 'node:fs/promises';
const fixture=JSON.parse(await fs.readFile('/tmp/artifact-fixture.json','utf8'));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('Console',m.text().slice(0,500))});page.on('requestfailed',r=>console.log('Failed',r.url(),r.failure()?.errorText));
await page.goto('http://127.0.0.1:3118/users/sign-in');
console.log('Login controls', await page.locator('input').evaluateAll(nodes=>nodes.map(n=>({type:n.type,name:n.name,placeholder:n.placeholder}))));
await page.locator('input[type=email]').fill('artifact-author@example.com');
await page.locator('input[type=password]').fill('Password123!');
await page.locator('button[type=submit]').click();
await page.waitForURL(url=>!url.pathname.includes('sign-in'),{timeout:45000});
await page.waitForTimeout(1500);
if(page.url().includes('onboarding')) { await page.getByText('Skip onboarding',{exact:true}).click(); await page.waitForTimeout(1500); }
await page.goto('http://127.0.0.1:3118/reports/'+fixture.report.id);
await page.getByText('Data & analytics',{exact:true}).waitFor({timeout:90000}).catch(()=>{});
const frame=page.frameLocator('iframe').first();
await frame.getByRole('button',{name:'Add note',exact:true}).waitFor({timeout:60000}).catch(()=>{});
console.log('Frame text',await page.frames()[1]?.locator('body').innerText());
console.log('Page text', (await page.locator('body').innerText()).slice(-2500));
console.log('Frames',page.frames().map(f=>f.url()));
await page.screenshot({path:'/tmp/artifact-initial.png',fullPage:false});
console.log('Errors',errors.slice(0,10));
await page.getByText('Data & analytics',{exact:true}).click();
await page.getByText('Launch checklist',{exact:true}).waitFor({timeout:30000});
await page.getByRole('dialog').evaluate(async el => { await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))) });
await page.screenshot({path:'media/pr/artifact-resources/data-explorer.png'});
await page.getByRole('button',{name:'Analytics',exact:true}).click();
await page.getByText('Authenticated unique viewers',{exact:true}).waitFor();
await page.screenshot({path:'media/pr/artifact-resources/analytics.png'});
await browser.close();
