import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire(new URL('../../../frontend/package.json',import.meta.url))('playwright');
const notebook=JSON.parse(await fs.readFile('/tmp/artifact-fixture.json','utf8'));
const document=JSON.parse(await fs.readFile('/tmp/artifact-document-fixture.json','utf8'));
const out='media/pr/artifact-resources';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'/tmp/artifact-qa-video',size:{width:1440,height:1000}}});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:3118/users/sign-in');
 await page.locator('input[type=email]').fill('artifact-author@example.com');
 await page.locator('input[type=password]').fill('Password123!');
 await page.locator('button[type=submit]').click();
 await page.waitForURL(u=>!u.pathname.includes('sign-in'));
 await page.goto('http://127.0.0.1:3118/reports/'+notebook.report.id);
 let frame=page.frameLocator('iframe').first();
 const note='Planning notes '+Date.now();
 await frame.getByLabel('Note title').fill(note);
 await frame.getByRole('button',{name:'Add note',exact:true}).click();
 await frame.getByText(note,{exact:true}).waitFor();
 await page.reload();frame=page.frameLocator('iframe').first();
 await frame.getByText(note,{exact:true}).waitFor();
 await page.screenshot({path:out+'/record-persisted.png'});
 await page.goto('http://127.0.0.1:3118/reports/'+document.report.id);
 frame=page.frameLocator('iframe').first();
 await frame.getByLabel('Choose document').setInputFiles({name:'weekly-plan.txt',mimeType:'text/plain',buffer:Buffer.from('Weekly plan: review open actions, assign owners, and record decisions for the next meeting.')});
 await frame.getByRole('button',{name:'Upload',exact:true}).click();
 await frame.getByText('Ready: weekly-plan.txt',{exact:true}).waitFor();
 await page.screenshot({path:out+'/file-upload.png'});
 const savedBefore=await frame.locator('article').count();
 await frame.getByRole('button',{name:'Summarize',exact:true}).click();
 await frame.locator('[aria-live=polite]').filter({hasText:'Key points:'}).waitFor();
 await frame.getByRole('button',{name:'Cancel',exact:true}).click();
 await frame.getByRole('alert').waitFor();
 assert.equal(await frame.getByRole('button',{name:'Save summary',exact:true}).count(),0);
 assert.equal(await frame.locator('article').count(),savedBefore);
 await frame.getByRole('button',{name:'Summarize',exact:true}).click();
 await frame.locator('[aria-live=polite]').filter({hasText:'Key points:'}).waitFor();
 await page.screenshot({path:out+'/streaming.png'});
 await frame.getByRole('button',{name:'Save summary',exact:true}).click();
 await frame.locator('article').nth(savedBefore).waitFor();
 await page.reload();frame=page.frameLocator('iframe').first();
 await frame.locator('article').filter({hasText:'weekly planning process'}).first().waitFor();
 await page.screenshot({path:out+'/summary-persisted.png'});
 await page.getByText('Data & analytics',{exact:true}).click();
 await page.getByRole('dialog').locator('table tbody tr').first().waitFor();
 await page.getByRole('dialog').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{})))});
 await page.screenshot({path:out+'/document-data.png'});
 await page.evaluate(()=>localStorage.setItem('bow.locale','he'));
 await page.reload();
 await page.getByText('נתונים וניתוח שימוש',{exact:true}).click();
 await page.getByRole('dialog').locator('table tbody tr').first().waitFor();
 await page.getByRole('dialog').evaluate(async el=>{await Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{})))});
 await page.screenshot({path:out+'/data-explorer-he.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: note persistence, real file upload, controlled-provider streaming/cancellation, explicit summary save/reload, read-only explorer and Hebrew UI');
} catch(e){await page.screenshot({path:'/tmp/artifact-interaction-failure.png'});console.error('Browser errors',errors);throw e}
finally{const video=page.video();await context.close();if(video)await video.saveAs(out+'/document-flow.webm');await browser.close()}
