import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
const seed = JSON.parse(fs.readFileSync(process.env.BOW_ERD_SEED || '/tmp/bow-tables-erd-run/seed.json', 'utf8'))
const id = seed.sqlite_sources[0].id
const headers = { Authorization: `Bearer ${seed.admin.token}`, 'X-Organization-Id': seed.organization.id }
const evidence = path.resolve('../media/pr/tables-erd')
const node = (page: any, name: string) => page.getByTestId(`erd-node-${name}`)
async function allTables(request: any) {
  const tables: any[] = []
  let page = 1
  while (true) {
    const response = await request.get(`${seed.base_url}/api/data_sources/${id}/full_schema?page=${page}&page_size=500`, {headers})
    expect(response.ok()).toBeTruthy()
    const data = await response.json()
    tables.push(...data.tables)
    if (!data.has_more) return {tables}
    page++
  }
}
async function reset(request: any) {
  expect((await request.put(`${seed.base_url}/api/organization/onboarding`, {headers, data:{dismissed:true,completed:false}})).ok()).toBeTruthy()
  expect((await request.post(`${seed.base_url}/api/data_sources/${id}/bulk_update_tables`, {headers, data:{action:'deactivate'}})).ok()).toBeTruthy()
  expect((await request.put(`${seed.base_url}/api/data_sources/${id}/update_tables_status`, {headers, data:{activate:['orders'],deactivate:[]}})).ok()).toBeTruthy()
}
test.beforeEach(async ({context, request}) => {
  await reset(request)
  await context.addCookies([{ name:'auth.token', value:seed.admin.token, domain:'127.0.0.1', path:'/' }])
  fs.mkdirSync(evidence,{recursive:true})
})
test('selected stroke and searchable selection menu', async ({page}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toHaveCSS('border-top-color', 'rgb(59, 130, 246)')
  await expect(node(page,'customers')).toHaveCSS('border-top-style','dotted')
  await expect(node(page,'orders').getByTestId('erd-connection-icon')).toBeVisible()
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.getByRole('button',{name:'Add tables',exact:true}).last().click()
  await expect(page.getByRole('option').first()).toContainText('orders')
  await expect(page.getByRole('option').first()).toHaveAttribute('aria-selected','true')
  await expect(page.getByRole('option').nth(1)).toHaveAttribute('aria-selected','false')
  await page.screenshot({path:path.join(evidence,'after-selection-menu.png')})
  await page.getByRole('combobox',{name:'Add tables'}).fill('products')
  await page.getByRole('option').filter({hasText:'products'}).click()
  await page.keyboard.press('Escape')
  await expect(node(page,'products')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
})
test('three states, exploration, shared filters and persisted selection', async ({page, request}) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByPlaceholder('Search tables...')).toBeVisible({timeout:60000})
  await page.locator('li').filter({has:page.getByText('orders',{exact:true})}).getByRole('checkbox').first().waitFor()
  if (process.env.BOW_ERD_BASELINE) {
    await page.screenshot({path:path.join(evidence,'before-agent-list-en.png')})
  }
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await expect(node(page,'customers')).toHaveAttribute('data-active','false')
  await expect(node(page,'line_items')).toHaveAttribute('data-active','false')
  await expect(node(page,'products')).toHaveCount(0)
  await expect(page.locator('.vue-flow__edge')).toHaveCount(seed.reference_connection_id ? 4 : 3)
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  await expect(node(page,'line_items')).toBeInViewport({ratio:0.99})
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-agent-canvas-en.png')})
  await node(page,'orders').click()
  await expect(page.getByTestId('erd-details')).toContainText('customer_id')
  await expect(page.getByTestId('erd-details')).toContainText('line_items')
  await page.getByRole('button',{name:'Clear focus',exact:true}).first().click()
  await node(page,'line_items').getByRole('button',{name:'+1 related'}).click()
  await expect(node(page,'products')).toHaveAttribute('data-active','false')
  await expect(node(page,'line_items')).toHaveAttribute('data-active','false')
  await node(page,'line_items').getByRole('checkbox').check()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await node(page,'customers').getByRole('button',{name:'Add',exact:true}).click()
  await page.getByRole('button',{name:'Table',exact:true}).click()
  await page.getByPlaceholder('Search tables...').fill('customers')
  await expect(page.getByText('Showing 1-1', {exact:false})).toBeVisible()
  await expect(page.locator('li').filter({has:page.getByText('customers',{exact:true})}).getByRole('checkbox')).toBeChecked()
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  const rows = await allTables(request)
  expect(rows.tables.filter((t:any)=>t.is_active).map((t:any)=>t.name).sort()).toEqual(['customers','line_items','orders'])
  await page.reload()
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await node(page,'customers').getByRole('checkbox').uncheck()
  await expect(node(page,'customers')).toHaveAttribute('data-active','false')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  expect(errors).toEqual([])
})
test('onboarding, search, bulk overrides, overlays, Hebrew and dark mode', async ({page, request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-onboarding-canvas-en.png')})
  await page.getByPlaceholder('Search tables...').fill('archive_')
  await expect(page.getByTestId('erd-discovery')).toContainText('archive_000')
  await page.getByRole('button',{name:`Select all (${seed.archive_count || 120})`,exact:true}).click()
  await expect(node(page,'archive_119')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'archive_000')).toBeInViewport({ratio:0.99})
  await expect(node(page,'archive_519')).toBeInViewport({ratio:0.99})
  await page.getByPlaceholder('Search tables...').fill('')
  await expect(page.getByTestId('erd-discovery')).toHaveCount(0)
  await page.screenshot({path:path.join(evidence,'after-large.png')})
  await page.getByPlaceholder('Search tables...').fill('archive_119')
  await page.getByTestId('erd-discovery').getByRole('button',{name:'archive_119',exact:true}).click()
  await expect(page.getByTestId('erd-visible-count')).toContainText(`${(seed.archive_count || 120) + (seed.reference_connection_id ? 5 : 4)} of`)
  await expect.poll(()=>page.locator('[data-testid^=erd-node-]').count()).toBeLessThan(50)
  await node(page,'archive_119').getByRole('checkbox').uncheck()
  await page.getByPlaceholder('Search tables...').fill('')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  const rows = await allTables(request)
  expect(rows.tables.filter((t:any)=>t.is_active)).toHaveLength(seed.archive_count || 120)
  expect(rows.tables.find((t:any)=>t.name==='archive_119').is_active).toBe(false)
  await reset(request)
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await page.getByRole('combobox',{name:'Overlay'}).selectOption('usage')
  await expect(node(page,'orders')).toContainText('Uses: 24')
  await page.getByRole('combobox',{name:'Overlay'}).selectOption('lastUsed')
  await expect(node(page,'orders')).toContainText('Sep 1, 2026')
  await page.getByRole('combobox',{name:'Overlay'}).selectOption('feedback')
  await expect(node(page,'orders')).toContainText('Answers: +8 / −1')
  await page.screenshot({path:path.join(evidence,'after-overlays.png')})
  await page.evaluate(()=>{localStorage.setItem('bow.locale','he');localStorage.setItem('nuxt-color-mode','dark')})
  await page.reload()
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('dir','rtl')
  await page.screenshot({path:path.join(evidence,'after-agent-canvas-he-dark.png')})
  await page.setViewportSize({width:1024,height:768})
  await page.getByRole('button',{name:'התאמת תצוגה',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-narrow.png')})
})

test('failed save preserves the draft and prevents onboarding navigation', async ({page,request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await node(page,'customers').getByRole('checkbox').check()
  await page.route('**/update_tables_status', route => route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Temporarily unavailable"}'}))
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page.getByText('Could not save table selection.',{exact:true})).toBeVisible()
  await expect(page).toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible()
  const persisted = await allTables(request)
  expect(persisted.tables.find((t:any)=>t.name==='customers').is_active).toBe(false)
  await page.unroute('**/update_tables_status')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
})

test('load retry, empty selection, keyboard discovery and self relationships', async ({page,request}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByPlaceholder('Search tables...').waitFor()
  await page.route('**/full_schema?page=1&page_size=500*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}))
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(page.getByText('Could not load relationships.',{exact:false})).toBeVisible()
  await page.unroute('**/full_schema?page=1&page_size=500*')
  await page.getByRole('button',{name:'Retry',exact:true}).click()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await page.getByPlaceholder('Search tables...').fill('employees')
  await page.getByTestId('erd-discovery').getByRole('button',{name:'employees',exact:true}).click()
  await expect(node(page,'employees')).toHaveAttribute('data-active','false')
  await node(page,'employees').getByRole('checkbox').focus()
  await page.keyboard.press('Space')
  await expect(node(page,'employees')).toHaveAttribute('data-active','true')
  await expect(page.locator('.vue-flow__edge-self')).toHaveCount(1)
  await page.getByPlaceholder('Search tables...').fill('')
  await expect(page.getByTestId('erd-discovery')).toHaveCount(0)
  await page.getByRole('button',{name:'Deselect all',exact:true}).click()
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(page.getByText('Add a table to explore its relationships.',{exact:true})).toBeVisible()
  await page.screenshot({path:path.join(evidence,'after-empty.png')})
})

test('reader sees selected tables only with no activation controls', async ({page,context,request}) => {
  await context.clearCookies()
  await context.addCookies([{name:'auth.token',value:seed.reader.token,domain:'127.0.0.1',path:'/'}])
  const readerHeaders = {...headers,Authorization:`Bearer ${seed.reader.token}`}
  const response = await request.get(`${seed.base_url}/api/data_sources/${id}/full_schema?page=1&page_size=500`,{headers:readerHeaders})
  expect(response.ok()).toBeTruthy()
  const data=await response.json()
  expect(data.tables.map((t:any)=>t.name)).toEqual(['orders'])
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByRole('button',{name:'ERD',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await expect(node(page,'customers')).toHaveCount(0)
  await expect(page.getByTestId('tables-erd').getByRole('checkbox')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Save',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Add tables',exact:true})).toHaveCount(0)
  await page.screenshot({path:path.join(evidence,'after-reader.png')})
})

test('late filtered list responses cannot replace the complete draft catalog', async ({page}) => {
  let releaseCatalog!: () => void
  let releaseList!: () => void
  let catalogStarted!: () => void
  let listStarted!: () => void
  const catalogGate = new Promise<void>(resolve => {releaseCatalog = resolve})
  const listGate = new Promise<void>(resolve => {releaseList = resolve})
  const catalogReady = new Promise<void>(resolve => {catalogStarted = resolve})
  const listReady = new Promise<void>(resolve => {listStarted = resolve})
  await page.goto(`/agents/${id}/tables`)
  const row = page.locator('li').filter({has:page.getByText('orders',{exact:true})})
  await row.getByRole('checkbox').uncheck()
  await page.route('**/full_schema?**', async route => {
    const url = new URL(route.request().url())
    if (url.searchParams.get('page_size') === '500' && url.searchParams.get('page') === '1') {
      const response = await route.fetch()
      catalogStarted()
      await catalogGate
      await route.fulfill({response})
    } else if (url.searchParams.get('page_size') === '100' && url.searchParams.get('search') === 'orders') {
      const response = await route.fetch()
      listStarted()
      await listGate
      await route.fulfill({response})
    } else await route.continue()
  })
  try {
    await page.getByRole('button',{name:'ERD',exact:true}).click()
    await catalogReady
    await page.getByRole('button',{name:'Filter tables',exact:true}).click()
    await page.getByRole('button',{name:'Unselected',exact:true}).click()
    await page.getByPlaceholder('Search tables...').fill('orders')
    await listReady
    releaseCatalog()
    await expect(page.getByTestId('tables-erd')).toBeVisible()
    await expect(page.getByTestId('erd-discovery')).toContainText('orders')
    const delayed = page.waitForResponse(response => response.url().includes('page_size=100') && response.url().includes('search=orders'))
    releaseList()
    await delayed
    await page.getByRole('button',{name:'Table',exact:true}).click()
    await expect(row.getByRole('checkbox')).toBeVisible()
    await expect(row.getByRole('checkbox')).not.toBeChecked()
    await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible()
  } finally {
    releaseCatalog()
    releaseList()
  }
})

test('suggested relationship spans real connections without activating its target', async ({page,request}) => {
  const rows = (await allTables(request)).tables
  const orders = rows.find((table:any)=>table.name==='orders')
  const companies = rows.find((table:any)=>table.name==='companies')
  expect(companies.connection_id).not.toBe(orders.connection_id)
  expect(orders.fks.some((fk:any)=>fk.references_name==='companies')).toBe(false)
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(node(page,'companies')).toHaveAttribute('data-active','false')
  await expect(node(page,'companies')).toContainText('Reference')
  await expect(node(page,'companies').getByTestId('erd-connection-icon').locator('img')).toHaveAttribute('src','/data_sources_icons/sqlite.png')
  await expect(page.locator('.erd-suggested-edge')).toHaveCount(1)
  await node(page,'orders').click()
  await expect(page.getByTestId('erd-details')).toContainText('Suggested from key names · unverified')
  await expect(page.getByTestId('erd-details')).toContainText('Reference')
  await page.screenshot({path:path.join(evidence,'after-cross-connection.png')})
  await page.getByRole('button',{name:'Clear focus',exact:true}).first().click()
  await node(page,'companies').getByRole('button',{name:'Add',exact:true}).click()
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  expect((await allTables(request)).tables.filter((table:any)=>table.is_active).map((table:any)=>table.name).sort()).toEqual(['companies','orders'])
})

test('connection filters stay shared in combined onboarding', async ({page,request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await page.getByRole('button',{name:'Filter tables',exact:true}).click()
  await page.locator('label').filter({hasText:'Reference'}).getByRole('checkbox').check()
  await page.getByRole('button',{name:'Filter tables',exact:true}).click()
  await expect(page.locator('li').filter({has:page.getByText('companies',{exact:true})})).toBeVisible()
  await expect(page.locator('li').filter({has:page.getByText('orders',{exact:true})})).toHaveCount(0)
  await page.getByRole('button',{name:'ERD',exact:true}).click()
  await expect(page.getByTestId('erd-discovery')).toContainText('companies')
  await expect(page.getByTestId('erd-discovery')).not.toContainText('orders')
  await page.getByRole('button',{name:'Add tables',exact:true}).last().click()
  await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(1)
  await page.getByRole('listbox').getByRole('option').click()
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  expect((await allTables(request)).tables.filter((table:any)=>table.is_active).map((table:any)=>table.name).sort()).toEqual(['companies','orders'])
})
