import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
// This spec drives the ERD against a stack seeded by tools/agent/seed_tables_canvas.py
// (specific tables, a reader user, a 120-table archive) and writes evidence screenshots.
// CI has no such seed. Reading it at module scope threw during collection, which aborted
// the entire Playwright run — every other spec in the suite was skipped as collateral —
// so the seed is now optional and its absence skips only this file.
const seedPath = process.env.BOW_ERD_SEED || '/tmp/bow-tables-erd-run/seed.json'
const hasSeed = fs.existsSync(seedPath)
test.skip(!hasSeed, `needs a seeded stack: run tools/agent/seed_tables_canvas.py, or point BOW_ERD_SEED at its seed.json (looked in ${seedPath})`)
const seed = hasSeed
  ? JSON.parse(fs.readFileSync(seedPath, 'utf8'))
  : { sqlite_sources: [{ id: '' }], admin: { token: '' }, reader: { token: '' }, organization: { id: '' }, base_url: '' }
const id = seed.sqlite_sources[0].id
const headers = { Authorization: `Bearer ${seed.admin.token}`, 'X-Organization-Id': seed.organization.id }
const evidence = path.resolve('../media/pr/tables-erd')
const node = (page: any, name: string) => page.getByTestId(`erd-node-${name}`)
async function allTables(request: any) {
  const tables: any[] = []
  let page = 1
  while (true) {
    const response = await request.get(`${seed.base_url}/api/data_sources/${id}/full_schema?page=${page}&page_size=500`, {headers})
    expect(response.ok()).toBeTruthy()
    const data = await response.json()
    tables.push(...data.tables)
    if (!data.has_more) return {tables}
    page++
  }
}
async function reset(request: any) {
  expect((await request.put(`${seed.base_url}/api/organization/onboarding`, {headers, data:{dismissed:true,completed:false}})).ok()).toBeTruthy()
  expect((await request.post(`${seed.base_url}/api/data_sources/${id}/bulk_update_tables`, {headers, data:{action:'deactivate'}})).ok()).toBeTruthy()
  expect((await request.put(`${seed.base_url}/api/data_sources/${id}/update_tables_status`, {headers, data:{activate:['orders'],deactivate:[]}})).ok()).toBeTruthy()
}
test.beforeEach(async ({context, request}) => {
  await reset(request)
  await context.addCookies([{ name:'auth.token', value:seed.admin.token, domain:'127.0.0.1', path:'/' }])
  fs.mkdirSync(evidence,{recursive:true})
})
test('compact toolbar, selected count, checkbox-only cards and hover metrics', async ({page}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(page.getByTestId('erd-select-tables')).toHaveText('1 selected')
  await expect(node(page,'customers').getByRole('button',{name:'Add',exact:true})).toHaveCount(0)
  await expect(node(page,'customers')).toHaveCSS('background-color','rgb(243, 244, 246)')
  await expect(page.getByRole('combobox',{name:'Overlay'})).toHaveCount(0)
  const view = await page.getByRole('button',{name:'Visual',exact:true}).boundingBox()
  const reload = await page.getByTestId('table-view-toolbar').getByRole('button',{name:'Reload',exact:true}).boundingBox()
  expect(Math.abs(view!.y - reload!.y)).toBeLessThan(6)
  await expect(node(page,'orders').getByTestId('erd-metrics')).toContainText('24')
  await node(page,'orders').getByTestId('erd-metrics').hover()
  await expect(page.getByTestId('table-metrics-details')).toContainText('22')
  await expect(page.getByTestId('table-metrics-details')).toContainText('Sep 1, 2026')
  const tooltip = page.getByTestId('table-metrics-details').locator('..')
  await expect(tooltip).toBeVisible()
  await expect(tooltip.locator('..')).toHaveCSS('opacity', '1')
  const tooltipBox = await tooltip.boundingBox()
  const lastMetricBox = await page.getByTestId('table-metrics-details').locator('div').last().boundingBox()
  expect(lastMetricBox!.y + lastMetricBox!.height).toBeLessThanOrEqual(tooltipBox!.y + tooltipBox!.height)
  await page.screenshot({path:path.join(evidence,'after-metrics-hover.png')})
})
test('selected stroke and searchable selection menu', async ({page}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toHaveCSS('border-top-color', 'rgb(59, 130, 246)')
  await expect(node(page,'customers')).toHaveCSS('border-top-style','dotted')
  await expect(node(page,'orders').getByTestId('erd-connection-icon')).toBeVisible()
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.getByTestId('erd-select-tables').click()
  await expect(page.getByRole('listbox')).not.toContainText('Selected')
  await expect(page.getByRole('listbox')).not.toContainText('Not selected')
  await expect(page.getByRole('option').first()).toContainText('orders')
  await expect(page.getByRole('option').first()).toHaveAttribute('aria-selected','true')
  await expect(page.getByRole('option').nth(1)).toHaveAttribute('aria-selected','false')
  await page.screenshot({path:path.join(evidence,'after-selection-menu.png')})
  await page.getByPlaceholder('Search tables…').fill('products')
  await page.getByRole('option').filter({hasText:'products'}).click()
  await page.keyboard.press('Escape')
  await expect(node(page,'products')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
})
test('three states, exploration, shared filters and persisted selection', async ({page, request}) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByPlaceholder('Search tables...')).toBeVisible({timeout:60000})
  await page.locator('li').filter({has:page.getByText('orders',{exact:true})}).getByRole('checkbox').first().waitFor()
  if (process.env.BOW_ERD_BASELINE) {
    await page.screenshot({path:path.join(evidence,'before-agent-list-en.png')})
  }
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await expect(node(page,'customers')).toHaveAttribute('data-active','false')
  await expect(node(page,'line_items')).toHaveAttribute('data-active','false')
  await expect(node(page,'products')).toHaveCount(0)
  await expect(page.locator('.vue-flow__edge')).toHaveCount(seed.reference_connection_id ? 4 : 3)
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  await expect(node(page,'line_items')).toBeInViewport({ratio:0.99})
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-agent-canvas-en.png')})
  await node(page,'orders').click()
  await expect(page.getByTestId('erd-details')).toContainText('customer_id')
  await expect(page.getByTestId('erd-details')).toContainText('line_items')
  await page.getByRole('button',{name:'Clear focus',exact:true}).first().click()
  await node(page,'line_items').getByRole('button',{name:'+1 related'}).click()
  await expect(node(page,'products')).toHaveAttribute('data-active','false')
  await expect(node(page,'line_items')).toHaveAttribute('data-active','false')
  await node(page,'line_items').getByRole('checkbox').check()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Clear focus',exact:true}).first().click()
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await node(page,'customers').getByRole('checkbox').check()
  await page.getByRole('button',{name:'List',exact:true}).click()
  await page.getByPlaceholder('Search tables...').fill('customers')
  await expect(page.getByText('Showing 1-1', {exact:false})).toBeVisible()
  await expect(page.locator('li').filter({has:page.getByText('customers',{exact:true})}).getByRole('checkbox')).toBeChecked()
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  const rows = await allTables(request)
  expect(rows.tables.filter((t:any)=>t.is_active).map((t:any)=>t.name).sort()).toEqual(['customers','line_items','orders'])
  await page.reload()
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await node(page,'customers').getByRole('checkbox').uncheck()
  await expect(node(page,'customers')).toHaveAttribute('data-active','false')
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  expect(errors).toEqual([])
})
test('onboarding, search, bulk overrides, metrics, Hebrew and dark mode', async ({page, request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  if (seed.reference_connection_id) await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-onboarding-canvas-en.png')})
  await page.getByPlaceholder('Search tables...').fill('archive_')
  await expect(page.getByTestId('erd-discovery')).toContainText('archive_000')
  await page.getByRole('button',{name:`Select all (${seed.archive_count || 120})`,exact:true}).click()
  await expect(node(page,'archive_119')).toHaveAttribute('data-active','true')
  await page.getByRole('button',{name:'Fit view',exact:true}).click()
  await expect(node(page,'archive_000')).toBeInViewport({ratio:0.99})
  await expect(node(page,'archive_519')).toBeInViewport({ratio:0.99})
  await page.getByPlaceholder('Search tables...').fill('')
  await expect(page.getByTestId('erd-discovery')).toHaveCount(0)
  await page.screenshot({path:path.join(evidence,'after-large.png')})
  await page.getByPlaceholder('Search tables...').fill('archive_119')
  await page.getByTestId('erd-discovery').getByRole('button',{name:'archive_119',exact:true}).click()
  await expect(page.getByTestId('erd-visible-count')).toContainText(`${(seed.archive_count || 120) + (seed.reference_connection_id ? 5 : 4)} of`)
  await expect.poll(()=>page.locator('[data-testid^=erd-node-]').count()).toBeLessThan(50)
  await node(page,'archive_119').getByRole('checkbox').uncheck()
  await page.getByPlaceholder('Search tables...').fill('')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  const rows = await allTables(request)
  expect(rows.tables.filter((t:any)=>t.is_active)).toHaveLength(seed.archive_count || 120)
  expect(rows.tables.find((t:any)=>t.name==='archive_119').is_active).toBe(false)
  await reset(request)
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await expect(node(page,'orders').getByTestId('erd-metrics')).toContainText('24')
  await node(page,'orders').getByTestId('erd-metrics').hover()
  await expect(page.getByTestId('table-metrics-details')).toContainText('Sep 1, 2026')
  await expect(page.getByTestId('table-metrics-details')).toContainText('+8 / −1')
  await expect(page.getByTestId('table-metrics-details').locator('../..')).toHaveCSS('opacity', '1')
  await page.screenshot({path:path.join(evidence,'after-overlays.png')})
  await page.evaluate(()=>{localStorage.setItem('bow.locale','he');localStorage.setItem('nuxt-color-mode','dark')})
  await page.reload()
  await expect(page.getByRole('button',{name:'חזותי',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'חזותי',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('dir','rtl')
  const rtlCanvas = await page.getByTestId('tables-erd').boundingBox()
  const rtlSave = await page.getByRole('button',{name:'Save',exact:true}).boundingBox()
  expect(rtlSave!.x).toBeLessThan(rtlCanvas!.x + 40)
  await page.screenshot({path:path.join(evidence,'after-agent-canvas-he-dark.png')})
  await page.setViewportSize({width:1024,height:768})
  await page.getByRole('button',{name:'התאמת תצוגה',exact:true}).click()
  await expect(node(page,'customers')).toBeInViewport({ratio:0.99})
  await page.screenshot({path:path.join(evidence,'after-narrow.png')})
})

test('failed save preserves the draft and prevents onboarding navigation', async ({page,request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await node(page,'customers').getByRole('checkbox').check()
  await page.route('**/update_tables_status', route => route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Temporarily unavailable"}'}))
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page.getByText('Could not save table selection.',{exact:true})).toBeVisible()
  await expect(page).toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  await expect(node(page,'customers')).toHaveAttribute('data-active','true')
  await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible()
  const persisted = await allTables(request)
  expect(persisted.tables.find((t:any)=>t.name==='customers').is_active).toBe(false)
  await page.unroute('**/update_tables_status')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
})

test('load retry, empty selection, keyboard discovery and self relationships', async ({page,request}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByPlaceholder('Search tables...').waitFor()
  await page.route('**/full_schema?page=1&page_size=500*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}))
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(page.getByText('Could not load relationships.',{exact:false})).toBeVisible()
  await page.unroute('**/full_schema?page=1&page_size=500*')
  await page.getByRole('button',{name:'Retry',exact:true}).click()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
  await page.getByPlaceholder('Search tables...').fill('employees')
  await page.getByTestId('erd-discovery').getByRole('button',{name:'employees',exact:true}).click()
  await expect(node(page,'employees')).toHaveAttribute('data-active','false')
  await node(page,'employees').getByRole('checkbox').focus()
  await page.keyboard.press('Space')
  await expect(node(page,'employees')).toHaveAttribute('data-active','true')
  await expect(page.locator('.vue-flow__edge-self')).toHaveCount(1)
  await page.getByPlaceholder('Search tables...').fill('')
  await expect(page.getByTestId('erd-discovery')).toHaveCount(0)
  await page.getByRole('button',{name:'Deselect all',exact:true}).click()
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(page.getByText('Add a table to explore its relationships.',{exact:true})).toBeVisible()
  await page.screenshot({path:path.join(evidence,'after-empty.png')})
})

test('reader sees selected tables only with no activation controls', async ({page,context,request}) => {
  await context.clearCookies()
  await context.addCookies([{name:'auth.token',value:seed.reader.token,domain:'127.0.0.1',path:'/'}])
  const readerHeaders = {...headers,Authorization:`Bearer ${seed.reader.token}`}
  const response = await request.get(`${seed.base_url}/api/data_sources/${id}/full_schema?page=1&page_size=500`,{headers:readerHeaders})
  expect(response.ok()).toBeTruthy()
  const data=await response.json()
  expect(data.tables.map((t:any)=>t.name)).toEqual(['orders'])
  await page.goto(`/agents/${id}/tables`)
  await expect(page.getByRole('button',{name:'Visual',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  await expect(node(page,'customers')).toHaveCount(0)
  await expect(page.getByTestId('tables-erd').getByRole('checkbox')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Save',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Add tables',exact:true})).toHaveCount(0)
  await node(page,'orders').locator('.font-mono').first().click()
  await expect(page.getByTestId('erd-details')).toBeVisible()
  await expect(page.getByTestId('table-recent-prompts')).toHaveCount(0)
  const prompts = await request.get(`${seed.base_url}/api/data_sources/${id}/tables/${data.tables[0].id}/recent-prompts`, {headers:readerHeaders})
  expect(prompts.status()).toBe(403)
  await page.screenshot({path:path.join(evidence,'after-reader.png')})
})

test('late filtered list responses cannot replace the complete draft catalog', async ({page}) => {
  let releaseCatalog!: () => void
  let releaseList!: () => void
  let catalogStarted!: () => void
  let listStarted!: () => void
  const catalogGate = new Promise<void>(resolve => {releaseCatalog = resolve})
  const listGate = new Promise<void>(resolve => {releaseList = resolve})
  const catalogReady = new Promise<void>(resolve => {catalogStarted = resolve})
  const listReady = new Promise<void>(resolve => {listStarted = resolve})
  await page.goto(`/agents/${id}/tables`)
  const row = page.locator('li').filter({has:page.getByText('orders',{exact:true})})
  await row.getByRole('checkbox').uncheck()
  await page.route('**/full_schema?**', async route => {
    const url = new URL(route.request().url())
    if (url.searchParams.get('page_size') === '500' && url.searchParams.get('page') === '1') {
      const response = await route.fetch()
      catalogStarted()
      await catalogGate
      await route.fulfill({response})
    } else if (url.searchParams.get('page_size') === '100' && url.searchParams.get('search') === 'orders') {
      const response = await route.fetch()
      listStarted()
      await listGate
      await route.fulfill({response})
    } else await route.continue()
  })
  try {
    await page.getByRole('button',{name:'Visual',exact:true}).click()
    await catalogReady
    await page.getByRole('button',{name:'Filter tables',exact:true}).click()
    await page.screenshot({path:path.join(evidence,'after-loading-filter-menu.png')})
    await page.getByRole('button',{name:'Unselected',exact:true}).click()
    await page.getByPlaceholder('Search tables...').fill('orders')
    await listReady
    releaseCatalog()
    await expect(page.getByTestId('tables-erd')).toBeVisible()
    await expect(page.getByTestId('erd-discovery')).toContainText('orders')
    const delayed = page.waitForResponse(response => response.url().includes('page_size=100') && response.url().includes('search=orders'))
    releaseList()
    await delayed
    await page.getByRole('button',{name:'List',exact:true}).click()
    await expect(row.getByRole('checkbox')).toBeVisible()
    await expect(row.getByRole('checkbox')).not.toBeChecked()
    await expect(page.getByText('Unsaved changes',{exact:true})).toBeVisible()
  } finally {
    releaseCatalog()
    releaseList()
  }
})

test('suggested relationship spans real connections without activating its target', async ({page,request}) => {
  const rows = (await allTables(request)).tables
  const orders = rows.find((table:any)=>table.name==='orders')
  const companies = rows.find((table:any)=>table.name==='companies')
  expect(companies.connection_id).not.toBe(orders.connection_id)
  expect(orders.fks.some((fk:any)=>fk.references_name==='companies')).toBe(false)
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'companies')).toHaveAttribute('data-active','false')
  await expect(node(page,'companies')).toContainText('Reference')
  await expect(node(page,'companies').getByTestId('erd-connection-icon').locator('img')).toHaveAttribute('src','/data_sources_icons/sqlite.png')
  await expect(page.locator('.erd-suggested-edge')).toHaveCount(1)
  await node(page,'orders').click()
  await expect(page.getByTestId('erd-details')).toContainText('Suggested from key names · unverified')
  await expect(page.getByTestId('erd-details')).toContainText('Reference')
  await expect(node(page,'companies')).toBeInViewport({ratio:0.99})
  await page.getByTestId('erd-details').getByText('orders.company_id → companies.id',{exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:path.join(evidence,'after-cross-connection.png')})
  await page.getByRole('button',{name:'Clear focus',exact:true}).first().click()
  await node(page,'companies').getByRole('checkbox').check()
  await page.getByRole('button',{name:'Save',exact:true}).click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  expect((await allTables(request)).tables.filter((table:any)=>table.is_active).map((table:any)=>table.name).sort()).toEqual(['companies','orders'])
})

test('connection filters stay shared in combined onboarding', async ({page,request}) => {
  await page.goto(`/onboarding/data/${id}/schema`)
  await page.getByRole('button',{name:'Filter tables',exact:true}).click()
  await page.locator('label').filter({hasText:'Reference'}).getByRole('checkbox').check()
  await page.getByRole('button',{name:'Filter tables',exact:true}).click()
  await expect(page.locator('li').filter({has:page.getByText('companies',{exact:true})})).toBeVisible()
  await expect(page.locator('li').filter({has:page.getByText('orders',{exact:true})})).toHaveCount(0)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(page.getByTestId('erd-discovery')).toContainText('companies')
  await expect(page.getByTestId('erd-discovery')).not.toContainText('orders')
  await page.getByTestId('erd-select-tables').click()
  await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(1)
  await page.getByRole('listbox').getByRole('option').click()
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Save & Continue',exact:true}).click()
  await expect(page).not.toHaveURL(new RegExp(`/onboarding/data/${id}/schema`))
  expect((await allTables(request)).tables.filter((table:any)=>table.is_active).map((table:any)=>table.name).sort()).toEqual(['companies','orders'])
})

test('cached custom query shares draft and Save without requiring its source tables', async ({page,request,context}) => {
  const setting = (value:boolean) => request.put(`${seed.base_url}/api/organization/settings`, {headers,data:{config:{enable_custom_queries:{value}}}})
  expect((await setting(true)).ok()).toBeTruthy()
  const source = (await allTables(request)).tables.find((table:any)=>table.name==='orders')
  const name = `totals_${randomUUID().slice(0,4)}`
  let queryId: string | undefined
  try {
    const created = await request.post(`${seed.base_url}/api/connections/${source.connection_id}/custom-queries`, {headers,data:{name,definition_sql:'SELECT COUNT(*) AS order_count, COALESCE(SUM(total), 0) AS total FROM orders',refresh_interval_minutes:1440}})
    expect(created.ok(),await created.text()).toBeTruthy()
    queryId=(await created.json()).id
    const query = (await allTables(request)).tables.find((table:any)=>table.name===name)
    expect(query.custom_query_id).toBe(queryId)
    expect(query.last_refreshed_at).toMatch(/Z$/)
    expect(query.is_active).toBe(false)
    for (const field of ['definition_sql','artifact_path','artifact_key_enc','rls_policy']) expect(query).not.toHaveProperty(field)
    await request.post(`${seed.base_url}/api/data_sources/${id}/bulk_update_tables`, {headers,data:{action:'deactivate'}})
    await page.goto(`/agents/${id}/tables`)
    await page.getByPlaceholder('Search tables...').fill(name)
    const queryRow = page.getByTestId(`cq-row-${name}`)
    await queryRow.getByRole('checkbox').check()
    const queryLabel = queryRow.getByText(name,{exact:true})
    const edit = queryRow.getByRole('button',{name:`Edit ${name}`,exact:true})
    expect((await edit.boundingBox())!.x).toBeGreaterThan((await queryLabel.boundingBox())!.x)
    await page.screenshot({path:path.join(evidence,'after-custom-query-list-edit.png')})
    expect((await allTables(request)).tables.find((table:any)=>table.name===name).is_active).toBe(false)
    await page.getByRole('button',{name:'Visual',exact:true}).click()
    await expect(page.getByTestId('erd-loading')).toHaveCount(0,{timeout:60_000})
    await expect(node(page,name)).toHaveAttribute('data-active','true')
    await expect(node(page,name).getByTestId('erd-custom-query')).toBeVisible()
    await expect(node(page,'orders')).toHaveCount(0)
    await page.getByPlaceholder('Search tables...').fill('')
    await expect(page.getByTestId('erd-discovery')).toHaveCount(0)
    await expect(node(page,'orders')).toHaveCount(0)
    await page.screenshot({path:path.join(evidence,'after-custom-query.png')})
    await node(page,name).getByTestId('erd-metrics').hover()
    await expect(page.getByTestId('table-metrics-details')).toContainText('Cached')
    await expect(page.getByTestId('table-metrics-details').locator('../..')).toHaveCSS('opacity', '1')
    await page.screenshot({path:path.join(evidence,'after-custom-query-metrics.png')})
    await page.getByRole('button',{name:'Full screen',exact:true}).click()
    await node(page,name).getByRole('button',{name:`Edit ${name}`,exact:true}).click()
    await expect(page.getByTestId('custom-query-modal')).toBeVisible()
    await page.getByTestId('custom-query-modal').getByRole('button',{name:'Cancel',exact:true}).click()
    await page.getByRole('button',{name:'Exit full screen',exact:true}).click()
    await page.getByRole('button',{name:'Save',exact:true}).click()
    await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
    expect((await allTables(request)).tables.filter((table:any)=>table.is_active).map((table:any)=>table.name)).toEqual([name])
    await page.reload()
    await page.getByRole('button',{name:'Visual',exact:true}).click()
    await expect(node(page,name)).toHaveAttribute('data-active','true')
    await context.clearCookies()
    await context.addCookies([{name:'auth.token',value:seed.reader.token,domain:'127.0.0.1',path:'/'}])
    await page.reload()
    await page.getByRole('button',{name:'Visual',exact:true}).click()
    await expect(node(page,name).getByTestId('erd-custom-query')).toBeVisible()
    await expect(node(page,name).getByRole('checkbox')).toHaveCount(0)
    await expect(node(page,name).getByRole('button',{name:`Edit ${name}`,exact:true})).toHaveCount(0)
  } finally {
    if (queryId) await request.delete(`${seed.base_url}/api/connections/${source.connection_id}/custom-queries/${queryId}`,{headers})
    await setting(false)
  }
})

test('laptop canvas, full screen, wide columns and visible metrics', async ({page,request}) => {
  await page.setViewportSize({width:1366,height:768})
  await page.route('**/full_schema?*', async route => {
    const response = await route.fetch()
    const data = await response.json()
    for (const table of data.tables || []) if (table.name === 'orders') {
      const original = table.columns || []
      table.columns = [...original, ...Array.from({length:300-original.length},(_,i)=>({name:`field_${String(i+original.length).padStart(3,'0')}`,dtype:'TEXT'}))]
      table.centrality_score = 0.72
    }
    await route.fulfill({response,json:data})
  })
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  if (process.env.BOW_ERD_BASELINE) await page.screenshot({path:path.join(evidence,'before-workspace-laptop.png')})
  const enterFullscreen = page.getByRole('button',{name:'Full screen',exact:true})
  await expect(enterFullscreen).toBeVisible()
  const save = page.getByRole('button',{name:'Save',exact:true})
  const canvas = await page.getByTestId('tables-erd').boundingBox()
  const enterBounds = await enterFullscreen.boundingBox()
  expect(enterBounds!.x + enterBounds!.width).toBeGreaterThan(canvas!.x + canvas!.width - 48)
  expect(enterBounds!.y).toBeLessThan(canvas!.y + 48)
  expect((await save.boundingBox())!.x).toBeLessThan(canvas!.x+40)
  await page.screenshot({path:path.join(evidence,'after-workspace-laptop.png')})
  await enterFullscreen.click()
  const exitFullscreen = page.getByRole('button',{name:'Exit full screen',exact:true})
  await expect(exitFullscreen).toBeVisible()
  expect((await exitFullscreen.boundingBox())!.x).toBeGreaterThan((await page.getByTestId('tables-erd').boundingBox())!.x + (await page.getByTestId('tables-erd').boundingBox())!.width - 160)
  expect((await page.getByTestId('tables-erd').boundingBox())!.height).toBeGreaterThan(500)
  await save.focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button',{name:'Connections',exact:true})).toBeFocused()
  await node(page,'orders').getByRole('button',{name:'Columns (300)',exact:true}).click()
  const details = page.getByTestId('erd-details')
  await expect(details.getByPlaceholder('Search columns…')).toBeVisible()
  const flowBounds = await page.locator('.erd-flow').boundingBox()
  const dockBounds = await details.boundingBox()
  expect(flowBounds!.x + flowBounds!.width).toBeLessThanOrEqual(dockBounds!.x)
  await expect(details.getByTestId('erd-column')).toHaveCount(50)
  await details.getByPlaceholder('Search columns…').fill('field_299')
  await expect(details.getByTestId('erd-column')).toHaveCount(1)
  await expect(details).toContainText('field_299')
  await expect(node(page,'orders').getByTestId('erd-metrics')).toContainText('22')
  await node(page,'orders').getByTestId('erd-metrics').hover()
  await expect(page.getByTestId('table-metrics-details')).toContainText('0.72')
  await page.mouse.move(10,10)
  await page.screenshot({path:path.join(evidence,'after-workspace-fullscreen.png')})
  await node(page,'customers').getByRole('checkbox').check()
  await save.click()
  await expect(page.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
  expect((await allTables(request)).tables.find((table:any)=>table.name==='customers').is_active).toBe(true)
  await page.getByRole('button',{name:'List',exact:true}).click()
  await expect(page.getByRole('button',{name:'Exit full screen',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Full screen',exact:true})).toBeVisible()
  await expect(node(page,'orders')).toHaveAttribute('data-active','true')
})

test('recent prompts load on focus, paginate, reset, retry and localize', async ({page}) => {
  await page.setViewportSize({width:1366,height:768})
  let requests = 0
  page.on('request', request => { if (request.url().includes('/recent-prompts')) requests++ })
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(node(page,'orders')).toBeVisible()
  expect(requests).toBe(0)
  await page.getByRole('button',{name:'Full screen',exact:true}).click()
  await node(page,'orders').locator('.font-mono').first().click()
  const panel = page.getByTestId('table-recent-prompts')
  await expect(panel.getByRole('heading',{name:'Recent prompts'})).toBeVisible()
  await expect(panel).toHaveClass(/rounded-md/)
  await expect(panel.locator('li').first()).toHaveClass(/bg-white/)
  await expect(panel.locator('li')).toHaveCount(5)
  await panel.getByRole('button',{name:'Show more',exact:true}).click()
  await expect(panel.locator('li')).toHaveCount(7)
  await expect(panel.getByRole('button',{name:'Show more',exact:true})).toHaveCount(0)
  await page.getByTestId('erd-details').evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({path:path.join(evidence,'after-recent-prompts.png')})
  await node(page,'customers').locator('.font-mono').first().click()
  await expect(panel).toContainText('No recorded prompts for this table.')
  await expect(panel.locator('li')).toHaveCount(0)
  let release!: () => void
  const delayed = new Promise<void>(resolve => { release = resolve })
  let intercepted!: () => void
  const started = new Promise<void>(resolve => { intercepted = resolve })
  let firstRequest = true
  let delayedUrl = ''
  await page.route('**/recent-prompts?**', async route => {
    if (!firstRequest) { await route.continue(); return }
    firstRequest = false
    delayedUrl = route.request().url()
    intercepted()
    await delayed
    await route.fulfill({json:{items:[{execution_id:'stale',prompt:'Stale table prompt',used_at:'2026-09-01T00:00:00Z',success:true}],next_offset:null}})
  })
  await node(page,'orders').locator('.font-mono').first().click()
  await started
  await expect(panel.getByRole('status')).toContainText('Loading prompts')
  await node(page,'customers').locator('.font-mono').first().click()
  const responseFinished = page.waitForResponse(response => response.url() === delayedUrl)
  release()
  await (await responseFinished).finished()
  await page.unroute('**/recent-prompts?**')
  await expect(panel).toContainText('No recorded prompts for this table.')
  await expect(panel).not.toContainText('Stale table prompt')
  await page.route('**/recent-prompts?**', route => route.fulfill({status:503,json:{detail:'Synthetic failure'}}))
  await node(page,'orders').locator('.font-mono').first().click()
  await expect(panel.getByRole('alert')).toContainText('Could not load prompts.')
  await page.unroute('**/recent-prompts?**')
  await panel.getByRole('button',{name:'Retry',exact:true}).click()
  await expect(panel.locator('li')).toHaveCount(5)
  await page.evaluate(()=>{localStorage.setItem('bow.locale','he');localStorage.setItem('nuxt-color-mode','dark')})
  await page.reload()
  await page.getByRole('button',{name:'חזותי',exact:true}).click()
  await page.getByRole('button',{name:'מסך מלא',exact:true}).click()
  await node(page,'orders').locator('.font-mono').first().click()
  await expect(panel.getByRole('heading',{name:'בקשות אחרונות'})).toBeVisible()
  await expect(panel.locator('li')).toHaveCount(5)
  const rtlFlow = await page.locator('.erd-flow').boundingBox()
  const rtlDetails = await page.getByTestId('erd-details').boundingBox()
  expect(rtlFlow!.x).toBeGreaterThanOrEqual(rtlDetails!.x + rtlDetails!.width)
  await page.screenshot({path:path.join(evidence,'after-recent-prompts-he.png')})
})

test('visual spinner stays until catalog and diagram are ready', async ({page}) => {
  let release!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  await page.route('**/full_schema?**', async route => {
    if (route.request().url().includes('page_size=500')) await gate
    await route.continue()
  })
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  const spinner = page.getByTestId('erd-loading')
  try {
    await expect(spinner).toBeVisible()
    await expect(spinner.locator('svg')).toBeVisible()
    await expect(spinner.locator('..')).toHaveAttribute('aria-busy','true')
    await page.screenshot({path:path.join(evidence,'after-visual-loading.png')})
  } finally { release() }
  await expect(node(page,'orders')).toBeVisible()
  await expect(spinner).toHaveCount(0)
  await expect(page.getByTestId('tables-erd')).toHaveCSS('opacity','1')
  await page.screenshot({path:path.join(evidence,'after-visual-ready.png')})
})

test('column buttons open the focused table columns after switching and collapsing', async ({page}) => {
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await expect(page.getByTestId('erd-loading')).toHaveCount(0)
  const details = page.getByTestId('erd-details')
  for (const name of ['orders', 'customers', 'orders', 'payments']) {
    await node(page,name).getByRole('button',{name:/^Columns \(/}).click()
    await expect(details.getByPlaceholder('Search columns…')).toBeVisible()
    await expect(details.getByTestId('erd-column').first()).toBeVisible()
    await details.getByPlaceholder('Search columns…').fill('id')
    await details.locator('summary').click()
    await expect(details.getByPlaceholder('Search columns…')).toBeHidden()
  }
  await node(page,'orders').locator('.font-mono').first().click()
  await expect(details.getByTestId('table-recent-prompts').locator('li').first()).toBeVisible()
  await details.evaluate(el => { el.scrollTop = el.scrollHeight })
  await node(page,'orders').getByRole('button',{name:/^Columns \(/}).click()
  await expect(details.getByPlaceholder('Search columns…')).toBeInViewport({ratio:1})
  await expect(details.getByPlaceholder('Search columns…')).toBeFocused()
  await page.screenshot({path:path.join(evidence,'after-column-button.png')})
})

test('wizard expands within its dialog and keeps primary actions on the left', async ({page,request,context}) => {
  const locale = process.env.BOW_WIZARD_LOCALE || 'en'
  const messages = JSON.parse(fs.readFileSync(path.resolve(`../locales/${locale}.json`), 'utf8'))
  await context.addInitScript(locale => localStorage.setItem('bow.locale', locale), locale)
  await page.setViewportSize({width:1366,height:900})
  let createdId: string | undefined
  await page.route('**/llm_sync', route => route.fulfill({json:{}}))
  page.on('response', async response => {
    if (response.request().method()==='POST' && new URL(response.url()).pathname==='/api/data_sources' && response.ok()) createdId=(await response.json()).id
  })
  try {
    await page.goto('/agents')
    await page.getByRole('button',{name:messages.agentsPage.new,exact:true}).last().click()
    await page.getByRole('button',{name:`${messages.agentsPage.newAgent} ${messages.agentsPage.newAgentDesc}`,exact:true}).click()
    const baseline = Boolean(process.env.BOW_WIZARD_BASELINE)
    const wizard = baseline ? page.getByRole('dialog').locator('.p-5').first() : page.getByTestId('new-agent-wizard')
    await wizard.getByPlaceholder('e.g., Sales, Marketing, Finance').fill(`Canvas wizard ${randomUUID().slice(0,6)}`)
    await wizard.getByRole('button',{name:'Select connections',exact:true}).last().click()
    await page.getByRole('option').filter({hasText:'sqlite-1'}).first().click()
    await page.keyboard.press('Escape')
    await wizard.getByRole('switch').click()
    const save = wizard.getByRole('button',{name:'Save & Continue',exact:true})
    const cancel = wizard.getByRole('button',{name:messages.common.cancel,exact:true})
    if (!baseline) expect((await save.boundingBox())!.x).toBeLessThan((await cancel.boundingBox())!.x)
    await page.screenshot({path:path.join(evidence,baseline ? 'before-wizard-actions.png' : `after-wizard-actions-${locale}.png`)})
    await save.click()
    await wizard.getByRole('button',{name:messages.tableErd.erd,exact:true}).click()
    await expect(wizard.getByTestId('erd-loading')).toHaveCount(0)
    const normalWidth = (await wizard.boundingBox())!.width
    await wizard.getByRole('button',{name:messages.tableErd.fullscreen,exact:true}).click()
    if (baseline) {
      await page.screenshot({path:path.join(evidence,'before-wizard-expanded.png')})
      await expect(wizard.getByTestId('tables-erd')).toBeVisible()
    }
    await expect(wizard.getByRole('button',{name:messages.tableErd.exitFullscreen,exact:true})).toBeVisible()
    await expect.poll(async ()=>(await wizard.boundingBox())!.width).toBeGreaterThan(normalWidth)
    await expect(page.getByRole('dialog')).toHaveCount(1)
    await expect(wizard.getByTestId('tables-erd')).toBeVisible()
    const menu = wizard.getByTestId('erd-select-tables')
    await menu.click()
    await expect(page.getByRole('listbox')).toBeVisible()
    await page.getByPlaceholder(messages.tableErd.searchTables).fill('orders')
    await page.getByRole('option').filter({hasText:'orders'}).first().click()
    await page.keyboard.press('Escape')
    await expect(wizard.getByRole('button',{name:messages.tableErd.exitFullscreen,exact:true})).toBeVisible()
    if (!baseline) expect((await save.boundingBox())!.x).toBeLessThan((await cancel.boundingBox())!.x)
    await expect(save).toBeInViewport({ratio:1})
    await expect.poll(() => wizard.evaluate(el => { let current: Element | null = el; while (current) { if (getComputedStyle(current).opacity === '0' || getComputedStyle(current).visibility === 'hidden') return false; current = current.parentElement }; return true })).toBe(true)
    await page.screenshot({path:path.join(evidence,`after-wizard-expanded-${locale}.png`),animations:'disabled'})
    await wizard.getByPlaceholder('Search tables...').focus()
    await page.keyboard.press('Escape')
    await expect(wizard.getByRole('button',{name:messages.tableErd.exitFullscreen,exact:true})).toHaveCount(0)
    await save.click()
    await expect(wizard.getByRole('button',{name:'Finish',exact:true})).toBeVisible()
    expect((await wizard.getByRole('button',{name:'Finish',exact:true}).boundingBox())!.x).toBeLessThan((await cancel.boundingBox())!.x)
    await cancel.click()
    await expect(wizard).toHaveCount(0)
  } finally {
    if (createdId) await request.delete(`${seed.base_url}/api/data_sources/${createdId}`,{headers})
  }
})

test('visual cards allow longer table and source names', async ({page}) => {
  const tableName = 'Adventure Works Internet Sales / Detailed Customer Orders'
  const sourceName = 'AdventureWorks SSAS Production Warehouse — Sales and Customer Analytics'
  await page.route('**/full_schema?**', async route => {
    const response = await route.fetch()
    const data = await response.json()
    for (const table of data.tables || []) if (table.name==='orders') {
      table.name=tableName
      table.connection_name=sourceName
    }
    await route.fulfill({response,json:data})
  })
  await page.goto(`/agents/${id}/tables`)
  await page.getByRole('button',{name:'Visual',exact:true}).click()
  await page.getByRole('button',{name:'Full screen',exact:true}).click()
  const card = node(page,tableName)
  const name = card.getByTitle(tableName,{exact:true})
  await expect(name).toBeVisible()
  expect(await name.evaluate(el=>el.clientHeight)).toBeGreaterThan(20)
  expect(await name.evaluate(el=>el.scrollHeight<=el.clientHeight)).toBe(true)
  await expect(card.getByText(sourceName,{exact:true})).toBeVisible()
  expect(await card.getByText(sourceName,{exact:true}).evaluate(el=>el.scrollHeight<=el.clientHeight)).toBe(true)
  await page.screenshot({path:path.join(evidence,'after-long-table-names.png')})
})
