"""add_completion_feedbacks_table

Revision ID: 34420bdfc530
Revises: 569d24b5f050
Create Date: 2025-07-27 07:28:44.973477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34420bdfc530'
down_revision: Union[str, None] = '569d24b5f050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_feedbacks',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('completion_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['completions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('completion_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_feedbacks_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:

    with op.batch_alter_table('completion_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_feedbacks_id'))

    op.drop_table('completion_feedbacks')
    # ### end Alembic commands ###
