# Deployment Configuration
deployment:
  type: "self_hosted"

base_url: http://localhost:3000

database:
  url: sqlite:///db/app.db
  
features:
  allow_uninvited_signups: false
  allow_multiple_organizations: false
  verify_emails: false

google_oauth:
  enabled: true
  client_id: '${BOW_GOOGLE_CLIENT_ID}'
  client_secret: '${BOW_GOOGLE_CLIENT_SECRET}'

smtp_settings:
  host: "smtp.resend.com"
  port: 587
  username: "resend"
  password: ${BOW_SMTP_PASSWORD}

encryption_key: ${BOW_ENCRYPTION_KEY}

intercom:
  enabled: false
