# Deployment Configuration
deployment:
  type: "self_hosted"

base_url: http://localhost:3000A

database:
  url: sqlite:///db/app.db
  
features:
  allow_uninvited_signups: true
  allow_multiple_organizations: false
  verify_emails: false

google_oauth:
  enabled: false
  client_id: 'asdf'
  client_secret: 'asdfsdafdsaf'

smtp_settings:
  host: "smtp.resend.com"
  port: 587
  username: "resend"
  password: ${BOW_SMTP_PASSWORD}

encryption_key: ${BOW_ENCRYPTION_KEY}

intercom:
  enabled: false
