#!/usr/bin/env bash
# Download vendored JS libraries for airgapped artifact rendering.
# These libraries are used inside iframe sandboxes and headless browser rendering.
# Run this script during Docker build or local development setup.
set -euo pipefail

LIBS_DIR="${1:-frontend/public/libs}"
mkdir -p "$LIBS_DIR"

echo "Downloading vendored JS libraries to $LIBS_DIR ..."

# Tailwind CSS Play CDN (JIT compiler for runtime Tailwind in artifacts)
curl -sL "https://cdn.tailwindcss.com/3.4.16" \
  -o "$LIBS_DIR/tailwindcss-3.4.16.js"

# React 18 production UMD build
curl -sL "https://unpkg.com/react@18/umd/react.production.min.js" \
  -o "$LIBS_DIR/react-18.production.min.js"

# React 18 development UMD build (used in artifact iframe for readable error messages)
curl -sL "https://unpkg.com/react@18/umd/react.development.js" \
  -o "$LIBS_DIR/react-18.development.js"

# ReactDOM 18 production UMD build
curl -sL "https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" \
  -o "$LIBS_DIR/react-dom-18.production.min.js"

# ReactDOM 18 development UMD build
curl -sL "https://unpkg.com/react-dom@18/umd/react-dom.development.js" \
  -o "$LIBS_DIR/react-dom-18.development.js"

# Babel Standalone (JSX transpilation in browser)
curl -sL "https://unpkg.com/@babel/standalone/babel.min.js" \
  -o "$LIBS_DIR/babel-standalone.min.js"

# ECharts 5 (charting library)
curl -sL "https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js" \
  -o "$LIBS_DIR/echarts-5.min.js"

# PDF.js v3 (UMD build — exposes global `pdfjsLib`) + its worker, for the
# <BowFile> inline PDF viewer inside the artifact sandbox.
curl -sL "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js" \
  -o "$LIBS_DIR/pdf.min.js"
curl -sL "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js" \
  -o "$LIBS_DIR/pdf.worker.min.js"


# Lucide icons (UMD build — exposes global `lucide.icons`), used by the
# <Icon> sandbox global so generated dashboards get a real icon set offline.
curl -sL "https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js" \
  -o "$LIBS_DIR/lucide.min.js"

# ─── Fonts ───────────────────────────────────────────────────────────────────
# Open-licensed (SIL OFL) typefaces vendored as latin woff2 so artifact themes
# can pair real display/body/mono faces without reaching Google Fonts at render
# time (airgapped deployments). The generated artifact-fonts.css carries the
# @font-face rules with LOCAL urls; artifact_libs.py inlines them as data URIs
# for headless validation, thumbnails and the standalone HTML export.
FONTS_DIR="$LIBS_DIR/fonts"
mkdir -p "$FONTS_DIR"
FONTS_CSS="$LIBS_DIR/artifact-fonts.css"
GF_UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
{
  echo "/* Generated by scripts/download-vendor-libs.sh — vendored latin subsets of open (OFL) typefaces. */"
  echo "/* Families: see FONT_SPECS in that script. Do not edit by hand. */"
} > "$FONTS_CSS"

# "<file stem>|<css2 family query>"
FONT_SPECS=(
  "fraunces|Fraunces:opsz,wght@9..144,300..900"
  "fraunces-italic|Fraunces:ital,opsz,wght@1,9..144,300..900"
  "instrument-serif|Instrument+Serif"
  "instrument-serif-italic|Instrument+Serif:ital@1"
  "playfair-display|Playfair+Display:wght@400..900"
  "dm-serif-display|DM+Serif+Display"
  "bricolage-grotesque|Bricolage+Grotesque:opsz,wght@12..96,300..800"
  "sora|Sora:wght@300..800"
  "manrope|Manrope:wght@300..800"
  "plus-jakarta-sans|Plus+Jakarta+Sans:wght@300..800"
  "geist|Geist:wght@300..800"
  "inter|Inter:opsz,wght@14..32,300..800"
  "outfit|Outfit:wght@300..800"
  "dm-sans|DM+Sans:opsz,wght@9..40,300..800"
  "jetbrains-mono|JetBrains+Mono:wght@300..700"
  "ibm-plex-mono|IBM+Plex+Mono:wght@400;500"
)
for spec in "${FONT_SPECS[@]}"; do
  stem="${spec%%|*}"; fam="${spec#*|}"
  css="$(curl -sL -A "$GF_UA" "https://fonts.googleapis.com/css2?family=${fam}&display=swap" || true)"
  # Keep only the latin @font-face block and point its src at the local file.
  block="$(printf '%s\n' "$css" | awk '/\/\* latin \*\//{f=1; next} f && /^}/{print; exit} f{print}')"
  url="$(printf '%s\n' "$block" | grep -o 'https://[^)]*' | head -1)"
  if [ -z "$url" ]; then echo "WARN: no latin face for $fam (skipped)"; continue; fi
  curl -sL "$url" -o "$FONTS_DIR/$stem.woff2"
  printf '@font-face {\n%s\n}\n' "$(printf '%s\n' "$block" | grep -v '@font-face' | grep -v '^}' | sed "s#url([^)]*)#url(/libs/fonts/$stem.woff2)#")" >> "$FONTS_CSS"
done
echo "Vendored fonts:"; ls -lh "$FONTS_DIR"

echo "Vendored JS libraries downloaded:"
ls -lh "$LIBS_DIR"
