apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations: {{.Values.serviceAccount.annotations | toJson}}
imagePullSecrets:
  - name: {{.Values.serviceAccount.imagePullSecret}}