apiVersion: v2
name: bagofwords
description: Bag of words - a new ai data tool
type: application
version: 1.0.7
appVersion: 1.0.1
dependencies:
  - name: postgresql
    version: 16.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
