import { chromium } from '@playwright/test';
import fs from 'fs';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const ROOT='tests/mobile-ui/output';
fs.mkdirSync(ROOT,{recursive:true});
const EMAIL=process.env.EMAIL, PASS='TestPass123!';
const b=await chromium.launch({headless:true,executablePath:EXE});
const p=await b.newPage();
p.on('response',r=>{ if(r.url().includes('/auth/jwt/login')) console.log('LOGIN resp',r.status()); });
await p.goto('http://localhost:3000/users/sign-in',{waitUntil:'load'});
await p.waitForSelector('#email',{timeout:30000});
await p.waitForTimeout(1500);
await p.fill('#email',EMAIL);
await p.fill('#password',PASS);
await p.click('button[type="submit"]');
await p.waitForTimeout(6000);
const err=await p.locator('.text-red-500').textContent().catch(()=>null);
console.log('url',p.url(),'err',JSON.stringify(err));
await p.context().storageState({path:`${ROOT}/state.json`});
await b.close();
