import { chromium } from '@playwright/test';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const ROOT='tests/mobile-ui/output';
const b=await chromium.launch({headless:true,executablePath:EXE});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,storageState:`${ROOT}/state.json`});
const p=await ctx.newPage();
await p.goto('http://localhost:3000'+process.env.P,{waitUntil:'commit',timeout:90000});
await p.waitForTimeout(parseInt(process.env.W||'6000'));
await p.screenshot({path:`${ROOT}/${process.env.LABEL}.png`});
console.log('shot',process.env.LABEL);
await b.close();
